// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// NetworkRoutesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



class NetworkRoutesAPI {
    /**
     Get the current network type of the chain
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    class func getNetworkType(completion: @escaping ((_ data: NetworkTypeDTO?,_ error: Error?) -> Void)) {
        getNetworkTypeWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get the current network type of the chain
     - GET /network
     - Returns the current network type.
     - examples: [{contentType=application/json, example={
  "name" : "mijinTest",
  "description" : "catapult development network"
}}]

     - returns: RequestBuilder<NetworkTypeDTO> 
     */
    class func getNetworkTypeWithRequestBuilder() -> RequestBuilder<NetworkTypeDTO> {
        let path = "/network"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<NetworkTypeDTO>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
