// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.

import Foundation


/// The co-signature signed transaction.
public struct CosignatureSignedTransaction {
    /// Hash of parent aggregate transaction that has been signed by a cosignatory of the transaction.
    public let parentHash: [UInt8]
    /// Signatures generated by signing the parent aggregate transaction hash.
    public let signature: [UInt8]
    /// Signer of the cosignature transaction.
    public let signer: [UInt8]
}
