// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
// Configuration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

class Configuration {
	
	// This value is used to configure the date formatter that is used to serialize dates into JSON format. 
	// You must set it prior to encoding any dates, and it will only be read once. 
    static var dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ"
    
}