// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// AccountInfoDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class AccountInfoDTO: Codable {

    var meta: AccountMetaDTO
    var account: AccountDTO


    
    init(meta: AccountMetaDTO, account: AccountDTO) {
        self.meta = meta
        self.account = account
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(meta, forKey: "meta")
        try container.encode(account, forKey: "account")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        meta = try container.decode(AccountMetaDTO.self, forKey: "meta")
        account = try container.decode(AccountDTO.self, forKey: "account")
    }
}

