// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// BlockInfoDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class BlockInfoDTO: Codable {

    var meta: BlockMetaDTO
    var block: BlockDTO


    
    init(meta: BlockMetaDTO, block: BlockDTO) {
        self.meta = meta
        self.block = block
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(meta, forKey: "meta")
        try container.encode(block, forKey: "block")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        meta = try container.decode(BlockMetaDTO.self, forKey: "meta")
        block = try container.decode(BlockDTO.self, forKey: "block")
    }
}

