// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// BlockchainStorageInfoDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class BlockchainStorageInfoDTO: Codable {

    var numBlocks: Int
    var numTransactions: Int
    var numAccounts: Int


    
    init(numBlocks: Int, numTransactions: Int, numAccounts: Int) {
        self.numBlocks = numBlocks
        self.numTransactions = numTransactions
        self.numAccounts = numAccounts
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(numBlocks, forKey: "numBlocks")
        try container.encode(numTransactions, forKey: "numTransactions")
        try container.encode(numAccounts, forKey: "numAccounts")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        numBlocks = try container.decode(Int.self, forKey: "numBlocks")
        numTransactions = try container.decode(Int.self, forKey: "numTransactions")
        numAccounts = try container.decode(Int.self, forKey: "numAccounts")
    }
}

