// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// MosaicDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class MosaicDTO: Codable {

    var id: UInt64DTO
    var amount: UInt64DTO


    
    init(id: UInt64DTO, amount: UInt64DTO) {
        self.id = id
        self.amount = amount
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(id, forKey: "id")
        try container.encode(amount, forKey: "amount")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decode(UInt64DTO.self, forKey: "id")
        amount = try container.decode(UInt64DTO.self, forKey: "amount")
    }
}

