// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// MosaicNameDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class MosaicNameDTO: Codable {

    var parentId: UInt64DTO
    var mosaicId: UInt64DTO
    var name: String


    
    init(parentId: UInt64DTO, mosaicId: UInt64DTO, name: String) {
        self.parentId = parentId
        self.mosaicId = mosaicId
        self.name = name
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(parentId, forKey: "parentId")
        try container.encode(mosaicId, forKey: "mosaicId")
        try container.encode(name, forKey: "name")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        parentId = try container.decode(UInt64DTO.self, forKey: "parentId")
        mosaicId = try container.decode(UInt64DTO.self, forKey: "mosaicId")
        name = try container.decode(String.self, forKey: "name")
    }
}

