// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// MosaicIds.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class MosaicIds: Codable {

    var mosaicIds: [String]?


    
    init(mosaicIds: [String]?) {
        self.mosaicIds = mosaicIds
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(mosaicIds, forKey: "mosaicIds")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        mosaicIds = try container.decodeIfPresent([String].self, forKey: "mosaicIds")
    }
}

