// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// MosaicInfoDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class MosaicInfoDTO: Codable {

    var meta: NamespaceMosaicMetaDTO
    var mosaic: MosaicDefinitionDTO


    
    init(meta: NamespaceMosaicMetaDTO, mosaic: MosaicDefinitionDTO) {
        self.meta = meta
        self.mosaic = mosaic
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(meta, forKey: "meta")
        try container.encode(mosaic, forKey: "mosaic")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        meta = try container.decode(NamespaceMosaicMetaDTO.self, forKey: "meta")
        mosaic = try container.decode(MosaicDefinitionDTO.self, forKey: "mosaic")
    }
}

