// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// MultisigAccountGraphInfoDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class MultisigAccountGraphInfoDTO: Codable {

    var level: Int
    var multisigEntries: [MultisigAccountInfoDTO]


    
    init(level: Int, multisigEntries: [MultisigAccountInfoDTO]) {
        self.level = level
        self.multisigEntries = multisigEntries
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(level, forKey: "level")
        try container.encode(multisigEntries, forKey: "multisigEntries")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        level = try container.decode(Int.self, forKey: "level")
        multisigEntries = try container.decode([MultisigAccountInfoDTO].self, forKey: "multisigEntries")
    }
}

