// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// MultisigAccountInfoDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class MultisigAccountInfoDTO: Codable {

    var multisig: Multisig


    
    init(multisig: Multisig) {
        self.multisig = multisig
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(multisig, forKey: "multisig")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        multisig = try container.decode(Multisig.self, forKey: "multisig")
    }
}

