// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// NamespaceMosaicMetaDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class NamespaceMosaicMetaDTO: Codable {

    var active: Bool
    var index: Int
    var id: String


    
    init(active: Bool, index: Int, id: String) {
        self.active = active
        self.index = index
        self.id = id
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(active, forKey: "active")
        try container.encode(index, forKey: "index")
        try container.encode(id, forKey: "id")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        active = try container.decode(Bool.self, forKey: "active")
        index = try container.decode(Int.self, forKey: "index")
        id = try container.decode(String.self, forKey: "id")
    }
}

