// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// NodeTimeDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class NodeTimeDTO: Codable {

    var communicationTimestamps: CommunicationTimestamps


    
    init(communicationTimestamps: CommunicationTimestamps) {
        self.communicationTimestamps = communicationTimestamps
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(communicationTimestamps, forKey: "communicationTimestamps")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        communicationTimestamps = try container.decode(CommunicationTimestamps.self, forKey: "communicationTimestamps")
    }
}

