// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// TransactionIds.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class TransactionIds: Codable {

    var transactionIds: [String]?


    
    init(transactionIds: [String]?) {
        self.transactionIds = transactionIds
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(transactionIds, forKey: "transactionIds")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        transactionIds = try container.decodeIfPresent([String].self, forKey: "transactionIds")
    }
}

