// Copyright 2018 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.
//
// TransactionStatusDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



class TransactionStatusDTO: Codable {

    var group: String?
    var status: String
    var hash: String?
    var deadline: UInt64DTO?
    var height: UInt64DTO?


    
    init(group: String?, status: String, hash: String?, deadline: UInt64DTO?, height: UInt64DTO?) {
        self.group = group
        self.status = status
        self.hash = hash
        self.deadline = deadline
        self.height = height
    }
    

    // Encodable protocol methods

    func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(group, forKey: "group")
        try container.encode(status, forKey: "status")
        try container.encodeIfPresent(hash, forKey: "hash")
        try container.encodeIfPresent(deadline, forKey: "deadline")
        try container.encodeIfPresent(height, forKey: "height")
    }

    // Decodable protocol methods

    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        group = try container.decodeIfPresent(String.self, forKey: "group")
        status = try container.decode(String.self, forKey: "status")
        hash = try container.decodeIfPresent(String.self, forKey: "hash")
        deadline = try container.decodeIfPresent(UInt64DTO.self, forKey: "deadline")
        height = try container.decodeIfPresent(UInt64DTO.self, forKey: "height")
    }
}

